apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nef-ingress
  labels:
    app: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: validation-athens.com
      http:
        paths:
          - path: /nef
            pathType: Prefix
            backend:
              service:
                name: nef-backend
                port:
                  number: 80
          - path: /capif-mongo
            pathType: Prefix
            backend:
              service:
                name: capif-mongo-express
                port:
                  number: 8082
    - host: capifcore
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capifcore
                port:
                  number: 8080
