apiVersion: v1
kind: Service
metadata:
  name: fogusnetworkapp-svc-db
spec:
  selector:
    app: fogusnetworkapp-pod-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: fogusnetworkapp-svc-be
spec:
  selector:
    app: fogusnetworkapp-pod-be
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fogusnetworkapp-svc-fe
spec:
  selector:
    app: fogusnetworkapp-pod-fe
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200