apiVersion: v1
kind: ConfigMap
metadata:
  name: zorte-configmap
data:
  NEF_IP: nefemu
  NEF_PORT: "4443"
  NEF_USER: admin@my-email.com
  NEF_PASS: pass
  PATH_TO_CERTS: /zortenet_netapp/capif_onboarding
  CAPIF_HOSTNAME: capifcore
  CAPIF_PORT: "8080"
  CAPIF_PORT_HTTPS: "443"
  CAPIF_IP: capifcore
  NEF_CALLBACK_IP: zortenetapp
  NEF_CALLBACK_PORT: "5000"
  INFLUX_IP: influxdb
  INFLUX_PORT: "8086"
