apiVersion: v1
kind: Service
metadata:
  name: zortenetapp
spec:
  selector:
    app: zortenetapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086