apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: api-invoker-management
spec:
  selector:
    app: api-invoker-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-provider-management
spec:
  selector:
    app: api-provider-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logs
spec:
  selector:
    app: logs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-apis
spec:
  selector:
    app: service-apis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: capif-events
spec:
  selector:
    app: capif-events
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-invocation-logs
spec:
  selector:
    app: api-invocation-logs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: published-apis
spec:
  selector:
    app: published-apis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: capif-routing-info
spec:
  selector:
    app: capif-routing-info
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: capif-security
spec:
  selector:
    app: capif-security
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: easy-rsa
spec:
  selector:
    app: easy-rsa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jwtauth
spec:
  selector:
    app: jwtauth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: capif-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: capif-mongo-express
spec:
  selector:
    app: capif-mongo-express
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: capifcore
spec:
  selector:
    app: nginx
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 443
