apiVersion: v1
kind: Service
metadata:
  name: iqbnetapp
spec:
  selector:
    app: iqbnetapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8980
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: callbacks
spec:
  selector:
    app: callbacks
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002